#ifndef PARSER_H
#define PARSER_H

#include <memory>
#include <vector>
#include <map>
#include <string>
#include "AST.h"
#include "token.h"
#include "symbol_table.h"
#include "running_opts.h"
#include "environment.h"

/**
 * @enum ErrorPhase
 * @brief Compilation phase a parser error belongs to
 */
enum class ErrorPhase {SYNTACTIC, SEMANTIC};

/**
 * @class Parser 
 * @brief A predictive recursive descent parser for the language.
 * * This parser performs syntax analysis using an LL(1) grammar approach.
 * It reads a list of tokens from the input returns the syntax correctness of the code as output.
 */
class Parser{
    public:
    /**
     * @brief Constructs a new Parser object.
     * 
     * @param tokenss The stream of tokens generated by the Lexer.
     * @param symbol_tablee A reference to the Symbol Table.
     */
    Parser(const std::vector<Token>& tokenss, RunningOptions opts); 

    /**
     * @brief Initiates the parsing process.
     * * Acts as the main entry point for syntax analysis, starting from the
     * root production rule (Prog) and ensuring the entire token stream is consumed.
     * * @returns the abstract syntax tree
     * * @throws runtime_error If extra tokens are found after the end of the program. 
     */
    AST parse();

    Environment& getEnv(){return env;}

    private:
    std::vector<Token> tokens;  ///< Token stream provided by the lexer
    size_t lookahead = 0;       ///< Current index pointing to the token being analyzed
    RunningOptions m_running_opts;
    Environment env;
    /**
     * @brief Retrieves the current token without consuming it.
     * @return Token The token at the current lookahead index, or EOF if out of bounds.
     */
    Token peek();

    /**
     * @brief Retrieves the next token in the stream without consuming it.
     * @return Token The token at lookahead+1, or EOF if out of bounds.
     */
    Token peek_next();

    /**
     * @brief Retrieves the most recently consumed token.
     * @return Token The token located immediately before the current lookahead index.
     */
    Token previous();

    /**
     * @brief Checks whether the current token can start a command.
     * @return true If lookahead is an .identifier "if", "while" or "System".
     * @return false Otherwise.
     */
    bool peek_Cmd();

    /**
     * @brief Consumes the current token if it matches the expected type.
     * * If the current type does not match the expected type, this method
     * immediately stops execution and throws a syntax error.
     * @param expected_type The TokenType that the parser expects to find.
     * @param custom_msg An optional custom error message to display upon failure.
     */
    void match(TokenType expected_type, const std::string& custom_msg = ""); 

    /**
     * @brief Throws a runtime error interrupting the compilation process.
     * @param msg The error information to display 
     * @param phase the phase (SYNTACTIC or SEMANTIC) used in the label
     */
    void throw_error(const std::string& msg, ErrorPhase phase = ErrorPhase::SYNTACTIC); 


    /*==============================[GRAMMAR PRODUCTION RULES]==============================*/
    
    /** @brief Parses the root program structure and returns the AST root */
    unique_ptr<ASTNode> parse_Prog();

    /** @brief Parses the main class and returns its MainDecl node */
    unique_ptr<ASTNode> parse_MainC();

    /** @brief Parses the class declaration and returns their ClassDecl nodes */
    vector<unique_ptr<ASTNode>> parse_DefCl();

    /** @brief Parses variable declarations into VarDecl nodes */
    vector<unique_ptr<ASTNode>> parse_DefVar();

    /** @brief Parses method declarations into MethodDecl nodes */
    vector<unique_ptr<ASTNode>> parse_DefMet();

    /** @brief Parses data types and returns it as a string */
    string parse_Type();

    /** @brief Parses a list of arguments into VarDecl nodes */
    vector<unique_ptr<ASTNode>> parse_Args();

    /** @brief Parses a non-empty command list */
    vector<unique_ptr<ASTNode>> parse_Lcom();
    
    /** @brief Parses a single command and returns its node */
    unique_ptr<ASTNode> parse_Cmd();

    /** @brief Parses a list of expressions (e.g., method call args). */
    vector<unique_ptr<ExprNode>> parse_ListExp();

    /*
    * Expression precedence cascade (lowest → highest):
    *   Exp → And_exp → Rel_exp → Add_exp → Mul_exp → Un_exp → Psf_exp → Pri_exp
    */

    /** @brief Parses an expression (entry point) */
    unique_ptr<ExprNode> parse_Exp();

    /** @brief Parses logical AND; build AndExpr nodes */
    unique_ptr<ExprNode> parse_And_exp();

    /** @brief Parses relational comparison (>); builds RelExpr nodes */
    unique_ptr<ExprNode> parse_Rel_exp();

    /** @brief Parses additive operators (+ / -); builds AddExpr nodes */
    unique_ptr<ExprNode> parse_Add_exp();

    /** @brief Parses multiplicative operator (*); builds MulDivExpr nodes */
    unique_ptr<ExprNode> parse_Mul_exp();

    /** @brief Parses negation (!); builds NegateExpr nodes */
    unique_ptr<ExprNode> parse_Un_exp();

    /** @brief Parses postfix acces ([], .length, .method(...) etc); builds PrimaryAccesExpr nodes */
    unique_ptr<ExprNode> parse_Psf_exp();

    /** @brief Parses a primary expression (highest precedence). */
    unique_ptr<ExprNode> parse_Pri_exp();
};

#endif