#ifndef PARSER_H
#define PARSER_H

#include <vector>
#include <map>
#include <string>
#include "token.h"
#include "symbol_table.h"

/**
 * @class Parser 
 * @brief A predictive recursive descent parser for the language.
 * * This parser performs syntax analysis using an LL(1) grammar approach.
 * It reads a list of tokens from the input returns the syntax correctness of the code as output.
 */
class Parser{
    public:
    /**
     * @brief Constructs a new Parser object.
     * 
     * @param tokenss The stream of tokens generated by the Lexer.
     * @param symbol_tablee A reference to the Symbol Table.
     */
    Parser(const std::vector<Token>& tokenss, SymbolTable& symbol_tablee); 

    /**
     * @brief Initiates the parsing process.
     * * Acts as the main entry point for syntax analysis, starting from the
     * root production rule (Prog) and ensuring the entire token stream is consumed.
     * * @throws runtime_error If extra tokens are found after the end of the program. 
     */
    void parse();

    private:
    std::vector<Token> tokens;  ///< Token stream provided by the lexer
    SymbolTable& symbol_table;  ///< Reference to the symbol table
    size_t lookahead = 0;       ///< Current index pointing to the token being analyzed

    /**
     * @brief Retrieves the current token without consuming it.
     * @return Token The token at the current lookahead index, or EOF if out of bounds.
     */
    Token peek();

    /**
     * @brief Retrieves the next token in the stream without consuming it.
     * @return Token The token at lookahead+1, or EOF if out of bounds.
     */
    Token peek_next();

    /**
     * @brief Retrieves the most recently consumed token.
     * @return Token The token located immediately before the current lookahead index.
     */
    Token previous();

    /**
     * @brief Consumes the current token if it matches the expected type.
     * * If the current type does not match the expected type, this method
     * immediately stops execution and throws a syntax error.
     * @param expected_type The TokenType that the parser expects to find.
     * @param custom_msg An optional custom error message to display upon failure.
     */
    void match(TokenType expected_type, const std::string& custom_msg = ""); 

    /**
     * @brief Throws a runtime error interrupting the compilation process.
     * @param msg The error information to display alongside the line and column data.
     */
    void throw_error(const std::string& msg); 


    /*==============================[GRAMMAR PRODUCTION RULES]==============================*/
    
    /** @brief Parses the root program structure. */
    void parse_Prog();

    /** @brief Parses the main class and its method signature. */
    void parse_MainC();

    /** @brief Parses the class declaration and inheritances. */
    void parse_DefCl();

    /** @brief Parses variable declarations. */
    void parse_DefVar();

    /** @brief Parses method signatures and bodies. */
    void parse_DefMet();

    /** @brief Parses data types (int, boolean, identifiers and arrays). */
    void parse_Type();

    /** @brief Parses a list of arguments. */
    void parse_Args();

    /** @brief Parses ... */
    void parse_Lcom();
    
    /** @brief Parses execution commands (if/else, while, assignments, print). */
    void parse_Cmd();

    /** @brief Parses a list of expressions (e.g., method call args). */
    void parse_ListExp();

    void parse_Exp();
    void parse_And_exp();
    void parse_Rel_exp();
    void parse_Add_exp();
    void parse_Mul_exp();
    void parse_Un_exp();
    void parse_Psf_exp();
    void parse_Pri_exp();
};

#endif